### ISSUE TITLE
Reference data source

### ISSUE THREAD

**Issue by wouterpeere** [mitchute/SecondaryCoolantProps#12]
Dear

I was doing some calculations with scp, when I found out that the values differ from the textbook values I have, referring back to the VDI warmeatlas (https://detector-cooling.web.cern.ch/data/Table%208-3-1.htm).

E.g., when I enter propyleen glycol into scp, at 0°C, 25%, I get:

- rho :1025.8  instead of 1030
- specific heat: 3872 <=> 3950
- thermal conductivity: 0.449 <=> 0.47

I found this by looking at the resulting difference in Reynolds number, which was rather significant. Can you comment on this? Where does the data from scp originate from?

The code I used for the values above is:
```python
import scp
scp.propylene_glycol.PropyleneGlycol(0.25).rho(0)
scp.propylene_glycol.PropyleneGlycol(0.25).specific_heat(0)
scp.propylene_glycol.PropyleneGlycol(0.25).conductivity(0)
```

Best regards,
Wouter Peere

**Comment by wouterpeere** [comment]
I think the difference can be explained by mass % in scp and volume % in VDI.

**Comment by mitchute** [comment]
The code is based on the work by Melinder, 2010. It's cited in the docs here: https://secondarycoolantprops.readthedocs.io/en/latest/fluid_melinder.html

but I'll also add a note to the README. The Melinder correlations are based on mass fraction.
